// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DesignDesign design design
//
// swagger:model design.Design
type DesignDesign struct {

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// deleted at
	DeletedAt string `json:"deletedAt,omitempty"`

	// design
	Design string `json:"design,omitempty"`

	// fields
	Fields DesignAttrs `json:"fields,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// updated at
	UpdatedAt string `json:"updatedAt,omitempty"`

	// user Id
	UserID string `json:"userId,omitempty"`
}

// Validate validates this design design
func (m *DesignDesign) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this design design based on context it is used
func (m *DesignDesign) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DesignDesign) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DesignDesign) UnmarshalBinary(b []byte) error {
	var res DesignDesign
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
