// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PaginationPagination pagination pagination
//
// swagger:model pagination.Pagination
type PaginationPagination struct {

	// page
	Page int64 `json:"page,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this pagination pagination
func (m *PaginationPagination) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pagination pagination based on context it is used
func (m *PaginationPagination) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaginationPagination) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaginationPagination) UnmarshalBinary(b []byte) error {
	var res PaginationPagination
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
